"""
install transformers, langchain, langchain-huggingface
$ pip install -r requirments.txt
$ pip install python-dotenv
$ pip install torch

# for accelerate error
$ pip install acclerate

# for bitsandbytes format error
$ pip install bitsandbytes 

downloaded model files are saved to ~/.cache//huggingface/hub/
"""
# setup for HF_TOKEN injection
from dotenv import load_dotenv
load_dotenv()

from transformers import pipeline, BitsAndBytesConfig, AutoTokenizer

import torch

torch.cuda.empty_cache()
# print(torch.cuda.is_available())
# print(torch.cuda.get_device_name())

# Insert cache-cleaning command at the beginning of training loop or validation step
# to make PyTorch release unused cached memory back to GPU

''' Example-1: summarization from text generation. '''

text = "Three people were dead at the scene and another was taken to a hospital in unknown condition, the department in a statement. At least one of the deceased appeared to be a pedestrian on the ground when the crash happened. Fire Capt. Branden Silverman said at the scene.\
The helicopter crash occurred after two people were killed and others were injured in a crash between a Los Angeles Metro bus and a passenger vehicle on Nordhoff Street, according to the fire department.It said that the bus crash happened at 5:03 p.m. and that firefighters worked to free the trapped people and assess the bus passengers."

# summarization task became obsolete -> use text-generation
model_id = "Qwen/Qwen3-4B-Instruct-2507"

""" High-level pipeline() loads the model into 32-bits precision (FP32) 
    which forces 4-billion parameter model to consume nearly 16 GB of memory. 
    We need explicitly pass down quantization and data-type arguments 
    to the underlying model config within the pipeline.

    "NVIDIA RTX 5070 comes with 12 BG of VRAM"

    $ pip install bitsandbytes accelerate    
"""

tokenizer = AutoTokenizer.from_pretrained(
    "Qwen/Qwen2-7B-Instruct", 
    clean_up_tokenization_spaces=False  # <-- Add this line
)

# 1. Configure 4-bit quantization to fit your 7.53 GiB GPU (RTX 4060)
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,                      
    bnb_4bit_compute_dtype=torch.
    float16,bnb_4bit_quant_type="nf4"
)

# 2. Pass quantization settings directly via model_kwargs
model = pipeline(
    task="text-generation", 
    model=model_id,
    model_kwargs={
        "quantization_config": quantization_config,
        # "torch_dtype": torch.float16, torch_type was depricated
        "dtype": torch.float16,
        "device_map": "auto"    # Automatically maps layers to GPU
    }
)

# model = pipeline(task="text-generation", model=model_id)

messages = [
    {
        "role": "user",
        "content": "Summarize the following text in 3 bullet points:\n\n" + text
    }
]
"""
Core message roles:
    - system: sets the behavior, tone, and content
    - user: represents the questions or commands input by the human
    - assistant:represents the prior responses generated by the AI model

Example messages in code: json
[
  {"role": "system", "content": "You speak like a pirate."},
  {"role": "user", "content": "Hi, what is the weather today?"},
  {"role": "assistant", "content": "Ahoy matey! 'Tis clear skies ahead!"},
  {"role": "user", "content": "Should I wear a jacket?"}
]

Reason for using message array
1.  Context tracking: model reads the full list of previous messages to understand follow ups
2.  Role authority: separating system instructiions from user inputs prevents the user from
    overiding core safety or functional rules
3.  Chat templates: local models use specialized chat templates to cover the message list into
    the exact text tokens the model expects
"""

# out = model(messages)
out = model(messages, max_new_tokens=200)
print(out[0]["generated_text"][-1]["content"])



